# Generated by Django 4.1.7 on 2023-04-06 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_listing_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing, Shoes, and Accessories'), ('sport', 'Sporting Goods'), ('art', 'Collectibles and Art')], max_length=64),
        ),
    ]
