# Generated by Django 4.1.7 on 2023-04-07 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_active_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
